### ISSUE TITLE
throw warning when players join

### ISSUE THREAD

**Issue by lamya3** [ProjectsForAll/Pacifism#6]
```
[17:03:45 WARN]: java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'java.util.List host.plas.pacifism.database.PacifismDBOperator.execute(java.lang.String, java.util.function.Cons
umer, boolean)'
[17:03:45 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[17:03:45 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[17:03:45 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[17:03:45 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[17:03:45 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[17:03:45 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[17:03:45 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[17:03:45 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[17:03:45 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[17:03:45 WARN]: Caused by: java.lang.NoSuchMethodError: 'java.util.List host.plas.pacifism.database.PacifismDBOperator.execute(java.lang.String, java.util.function.Consumer, boolean)'
[17:03:45 WARN]:        at Pacifism-1.10.0.jar//host.plas.pacifism.database.PacifismDBOperator.alterTables(PacifismDBOperator.java:51)
[17:03:45 WARN]:        at Pacifism-1.10.0.jar//host.plas.pacifism.database.PacifismDBOperator.ensureUsable(PacifismDBOperator.java:42)
[17:03:45 WARN]:        at Pacifism-1.10.0.jar//host.plas.pacifism.database.PacifismDBOperator.lambda$loadPlayer$8(PacifismDBOperator.java:103)
[17:03:45 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[17:03:45 WARN]:        ... 6 more
```

version: Pacifism-1.10.0.jar
minecraft: LeavesMC 1.20.1
database: sqlite (default config.yml)

**Comment by DrakDv** [comment]
Please update BOU (BukkitOfUtils) to the latest version. Found here: [https://modrinth.com/plugin/bukkitofutils/versions](https://modrinth.com/plugin/bukkitofutils/versions)

**Comment by DrakDv** [comment]
Let me know if that solves your issue.

**Comment by lamya3** [comment]
yes it seems to be fixed sence I update BOU to 1.4.0, thank you. But it conflicts with another plugin ([LibertyBans](https://github.com/A248/LibertyBans)) ？

```
[20:35:39 INFO]: [BukkitOfUtils] Enabling BukkitOfUtils v1.4.0*
[20:35:39 INFO]: [BukkitOfUtils] [INFO] TaskManager is now initialized!
[20:35:39 INFO]: [BukkitOfUtils] [INFO] Callback Listener has been registered!
[20:35:39 INFO]: [BukkitOfUtils] [INFO] > [console] FireString Registered!
[20:35:39 INFO]: [BukkitOfUtils] [INFO] > [message] FireString Registered!
[20:35:39 INFO]: [BukkitOfUtils] [INFO] > [title] FireString Registered!
[20:35:39 INFO]: [BukkitOfUtils] [INFO] > [broadcast] FireString Registered!
[20:35:39 INFO]: [BukkitOfUtils] [INFO] > [broadcasttitle] FireString Registered!
[20:35:39 INFO]: [BukkitOfUtils] [INFO] Initialized FireStringManager with 5 FireStrings
[20:35:39 INFO]: [Pacifism] Enabling Pacifism v1.10.0*
[20:35:39 INFO]: [tv.quaint.thebase.lib.hikari.HikariDataSource] Pacifism - Pool - Starting...
[20:35:39 INFO]: [tv.quaint.thebase.lib.hikari.pool.HikariPool] Pacifism - Pool - Added connection org.sqlite.jdbc4.JDBC4Connection@49ea3f46
[20:35:39 INFO]: [tv.quaint.thebase.lib.hikari.HikariDataSource] Pacifism - Pool - Start completed.
[20:35:39 INFO]: [LibertyBans] Enabling LibertyBans v1.1.0-RC2
[20:35:39 WARN]: [LibertyBans] *******************************************
We have detected bugs on your server which threaten your server's stability.
LibertyBans will continue to operate unaffected, but we strongly suggest you fix these bugs.

These bugs are (most likely) due to other plugins' mistakes. Each of the following plugins has shaded a library but did not relocate it. You should report each bug to the plugin author.

Plugin Name | Library Name | Class Detected
----------------------------------------------
Plugin 'BukkitOfUtils 1.4.0' | HikariCP | com.zaxxer.hikari.HikariConfig
Plugin 'BukkitOfUtils 1.4.0' | Caffeine | com.github.benmanes.caffeine.cache.Caffeine

Note for advanced users: Understanding the consequences, you can minimize this warning by setting the system property libertybans.relocationbug.disablecheck to 'true'
*******************************************
[20:35:39 INFO]: [LibertyBans] No addons detected
[20:36:34 INFO]: [space.arim.libertybans.core.addon.AddonLoader] No addons loaded
[20:36:35 INFO]: [space.arim.libertybans.core.AbstractBaseFoundation] Conducting start phase...
[20:36:35 ERROR]: Error occurred while enabling LibertyBans v1.1.0-RC2 (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean org.bukkit.Server.isGlobalTickThread()'
        at space.arim.morepaperlib.scheduling.GracefulScheduling.isOnGlobalRegionThread(GracefulScheduling.java:146) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.isPrimaryThread0(BukkitFactoryOfTheFutureImpl.java:59) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.concurrent.MainThreadCachingFutureFactory.isPrimaryThread(MainThreadCachingFutureFactory.java:49) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.create(BukkitFactoryOfTheFutureImpl.java:53) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:56) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:45) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitPlatformHandleImpl.createFuturesFactory(BukkitPlatformHandle.java:64) ~[LibertyBans-ClassLoader:?]
        at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
        at space.arim.libertybans.core.service.StandardAsynchronicityManager.startup(StandardAsynchronicityManager.java:90) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.LifecycleGodfather.startup0(LifecycleGodfather.java:75) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.timedEvent(AbstractBaseFoundation.java:126) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.startup(AbstractBaseFoundation.java:64) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.env.spigot.plugin.SpigotPlugin.initialize(SpigotPlugin.java:112) ~[LibertyBans_Release-1.1.0-RC2.jar:?]
        at space.arim.libertybans.env.spigot.plugin.SpigotPlugin.onEnable(SpigotPlugin.java:48) ~[LibertyBans_Release-1.1.0-RC2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:649) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:560) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:629) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1095) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:36:35 INFO]: [LibertyBans] Disabling LibertyBans v1.1.0-RC2
[20:36:35 WARN]: [LibertyBans] LibertyBans wasn't launched; check your log for a startup error
```
It doesn't spam error if I use BOU version 1.3.0, so I'm not sure what (how) caused this ?

**Comment by DrakDv** [comment]
https://modrinth.com/plugin/bukkitofutils/version/j2fSFHR0
It should still work with out this update, but this should make the warning go away.

By the way, there is something wrong with your LibertyBans plugin. It looks like it is using an outdated version of GracefulScheduling. Although I'm not quite sure if that is the issue as I don't use GracefulScheduling.

I do know that it is not my plugin causing this.

**Comment by lamya3** [comment]
I reported this problem to LibertyBans. ‌‌Many thanks
